name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.20.4']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Gulp
      run: npm i gulp-cli --global 

    - name: NPM install
      run: npm install

    - name: Bundle SPFx
      run: gulp bundle --ship || true

    - name: Package SPFx
      run: gulp package-solution --ship || true

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: SPFx Package
        path: ./sharepoint/solution/spo-home-url.sppkg
